### ISSUE TITLE
Cancel feature

### ISSUE THREAD

**Issue by funkyburger** [funkyburger/ConnectionStringTest#18]

**Comment by jeffward01** [comment]
What is this feature?

**Comment by funkyburger** [comment]
Sometime, the test goes all the way to timeout when the user knows that it should respond much faster. In my case, i tested to a local db file.
Instead of waiting for 2 whole minutes, user could cancel and retest with other parameters right away.

**Comment by funkyburger** [comment]
Fixed in #26.
